repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-toml
  - id: check-docstring-first
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
  - id: name-tests-test
    args: [--pytest-test-first]
    exclude: (^tests/mock/|^tests/integration/fixtures)
  - id: check-merge-conflict
  - id: check-json

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-ini
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix, --indent, '2']

- repo: https://github.com/pappasam/toml-sort
  rev: v0.23.1
  hooks:
  - id: toml-sort
  - id: toml-sort-fix

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black, --line-length=120]

- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0
  hooks:
  - id: pycln

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    include: (src|tests)
    args: [--line-length=120]

- repo: https://github.com/sondrelg/pep585-upgrade
  rev: v1.0.1
  hooks:
  - id: upgrade-type-hints

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    include: (src|tests)
    args: [--config, .flake8]

- repo: local
  hooks:
  - id: pytest-unit
    name: unit tests
    entry: pytest -c ./tests/pytest-config.ini ./tests/unit
    language: system
    types: [python]
    pass_filenames: false
    always_run: true
